"""
This module should be able to be imported from anywhere without any dependencies, because it's used in setup.
"""

import textwrap

EXEC_OUTPUT_PYTHON = textwrap.dedent(
    """
    #!/usr/bin/env python3
    # GENERATED BY version-pioneer-{version_pioneer_version}
    # by evaluating the original _version.py file and storing the computed versions as a constant.

    __version_dict__ = {version_dict}
    __version__ = __version_dict__["version"]
    
    if __name__ == "__main__":
        import json

        print(json.dumps(__version_dict__))
    """
).strip()


SETUP_PY = textwrap.dedent("""
    from setuptools import setup
    from version_pioneer.build.setuptools import get_version, get_cmdclass

    setup(
        version=get_version(),
        cmdclass=get_cmdclass(),
    )
""")
